'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Alumno
    Public Property idAlumno As Integer
    Public Property nombre As String
    Public Property apellido As String

    Public Overridable Property AuxAlumnoGradoes As ICollection(Of AuxAlumnoGrado) = New HashSet(Of AuxAlumnoGrado)
    Public Overridable Property Notas As ICollection(Of Nota) = New HashSet(Of Nota)

End Class
