'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AuxMateriaProfesor
    Public Property idAuxMateriaProfesor As Integer
    Public Property idMateria As Integer
    Public Property idProfesor As Integer

    Public Overridable Property Materia As Materia
    Public Overridable Property Profesor As Profesor

End Class
