'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DetalleSalonSeccion
    Public Property idDetlleSalonSeccion As Integer
    Public Property idSalon As Integer
    Public Property idSeccion As Integer

    Public Overridable Property Salon As Salon
    Public Overridable Property Seccion As Seccion

End Class
