'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Materia
    Public Property idMateria As Integer
    Public Property nombre As String

    Public Overridable Property AuxMateriaGradoes As ICollection(Of AuxMateriaGrado) = New HashSet(Of AuxMateriaGrado)
    Public Overridable Property AuxMateriaProfesors As ICollection(Of AuxMateriaProfesor) = New HashSet(Of AuxMateriaProfesor)
    Public Overridable Property DetalleSalonMaterias As ICollection(Of DetalleSalonMateria) = New HashSet(Of DetalleSalonMateria)
    Public Overridable Property Notas As ICollection(Of Nota) = New HashSet(Of Nota)

End Class
