'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Nota
    Public Property idNota As Integer
    Public Property idAlumno As Integer
    Public Property idMateria As Integer
    Public Property bimestre As Integer
    Public Property valor As Integer

    Public Overridable Property Alumno As Alumno
    Public Overridable Property Materia As Materia

End Class
