'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Profesor
    Public Property idProfesor As Integer
    Public Property idDepartamento As Integer
    Public Property nombre As String
    Public Property apellido As String

    Public Overridable Property AuxMateriaProfesors As ICollection(Of AuxMateriaProfesor) = New HashSet(Of AuxMateriaProfesor)
    Public Overridable Property Departamento As Departamento

End Class
